### ISSUE TITLE
ip field in Server response can be null

### ISSUE THREAD

**Issue by Sirius708** [MathiasPius/hrobot-rs#5]
I have a dedicated server without an IPv4 Address, so only IPv6 subnet, and in the response of e.g. `get_server` or `list_servers`, the `ip` field is null, which means serde can't deserialize the response.

It looks like this is undocumented behavior, at least the Robot API docs have no example for this.

The relevant piece of code:

https://github.com/MathiasPius/hrobot-rs/blob/186d3ddedb83b45d00600e6c7f37d74fa262877d/src/api/server/models.rs#L141-L146

This could be fixed by either wrapping the Vec in an Option (I tried that locally, would be a breaking change), or using a custom deserialization function.

**Comment by MathiasPius** [comment]
Hey Sirius, thanks for opening the issue!

This is definitely an oversight on my part. All my servers have IPv4 addresses attached, and I wrongfully assumed `#[serde(default)]` would deserialize to an empty `Vec`, which is [apparently not the case](https://github.com/serde-rs/serde/issues/2173)

I'll see if I can't get a fix out the door before Monday, but if you're in a hurry you're very welcome to take a crack at it yourself :)

I think it'd also make sense to see if there are other places in the API where the same wrongful assumption is made.

**Comment by MathiasPius** [comment]
Should be fixed in the just-released v1.1.0

**Comment by Sirius708** [comment]
Thank you
